/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client;
import java.awt.Color;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.event.ActionEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class Forgot_pass extends javax.swing.JFrame {

    Connection conx = null;
    ResultSet resultat = null;
        PreparedStatement prepared = null;

        String emailPattern = "^[a-zA-Z0-9]+[@]+[a-zA-Z]+[.]+[a-zA-Z]+$";
        String passwordPattern = "^[a-zA-Z]+[0-9]+$";

    /**
     * Creates new form Forgot_pass
     */
    public Forgot_pass() {
        initComponents();
         this.setExtendedState(JFrame.MAXIMIZED_BOTH);

        Update.setEnabled(false);
        search.setEnabled(false);
        search.setForeground(new Color(0, 0, 0));
        Update.setForeground(new Color(0, 0, 0));
        txtquestion.setEditable(false);
        
        conx = ConnexionMySQL.ConnectDb();
    }

    public void clear(){
          Update.setEnabled(false);
        search.setEnabled(false);
        search.setForeground(new Color(0, 0, 0));
        Update.setForeground(new Color(0, 0, 0));
        
        txtemail.setText("");
        txtquestion.setText("");
        txtreponse.setText("");
        txtnew.setText("");
        txtconfirm.setText("");
    }
    
    public void validateEmail(){
        String email_user;
        
        email_user = txtemail.getText();
        
       if(email_user.matches(emailPattern)){
            
                        search.setEnabled(true);
                        search.setForeground(new Color(240, 240, 240));
                        search.setBackground(new Color(204, 102, 0));

        }
            
        else {
            
                          search.setEnabled(false);
                        search.setForeground(new Color(0, 0, 0));
                        search.setBackground(new Color(240, 240, 240));
        }  
        
    }
    /*
     public String Encrypt(String T){
        
       
String A = "";        
       
        char[] chars = T.toCharArray();
        
        for(char c : chars){
            
            c += 5;
           
           // System.out.print(c);
            A = A + c;
        }

            return A;
        
        
    
    }
    
    */
   
    public void Modifier(String password, String mail){
        
        if(password.matches(passwordPattern)){
            
             password = Encryption.Crypt(password, "Key");
        
        String sql = "Update client set Mot_de_passe = '"+password+"' where Email like '"+mail+"' ";
        
        
        try {
            
            
            
                    prepared = conx.prepareStatement(sql);
                    prepared.executeUpdate();
                    
                 
           JOptionPane.showMessageDialog(null, "Mot de passe mis à jour");

                Login Connexion = new Login();
                this.hide();
                Connexion.setVisible(true);
                
                 
                    
                    

        } catch (SQLException ex) {
          System.out.println(ex);
        }
        
        }
        
        else {
            
                       JOptionPane.showMessageDialog(null, "Format du mot de passe incorrect");

        }
       
        
    }
    
    public void validateFields(){
        String email_user;
        email_user = txtemail.getText();
        String Question = txtquestion.getText();
        String Reponse = txtreponse.getText();
        String pass = txtnew.getText();
        String Confirm = txtconfirm.getText();
        
      if((!email_user.equals("")) && (!Question.equals("")) && (!Reponse.equals("")) && (!pass.equals("")) && (!Confirm.equals(""))){
    
    Update.setEnabled(true);
}
      
      else {
          
          Update.setEnabled(false);
      }
            
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        txtquestion = new javax.swing.JTextField();
        txtreponse = new javax.swing.JTextField();
        Update = new javax.swing.JButton();
        txtnew = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        txtconfirm = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        search = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Récuperation du mot de passe");
        setResizable(false);

        panel1.setBackground(new java.awt.Color(204, 102, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1700918001206.jpg"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Vivaldi", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("Louez vite, partez plus loin");

        jLabel10.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(240, 240, 240));
        jLabel10.setText("Facebook :https://facebook/RenForYou.com");

        jLabel9.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("Téléphone : +25377585576");

        jLabel11.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(240, 240, 240));
        jLabel11.setText("E-mail : rentfortou@gmail.com");

        jLabel12.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(240, 240, 240));
        jLabel12.setText("Adresse : Quartier 5 Boulevard De Gaulle Rue Farahad");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(166, 166, 166))
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addGap(26, 26, 26))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 102, 0));
        jLabel2.setText("Réinitialisation du mot de passe");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("E-mail");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Question de securité");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Réponse");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Nouveau mot de passe");

        txtemail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtemail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtemailKeyReleased(evt);
            }
        });

        txtquestion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtquestion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtquestionKeyReleased(evt);
            }
        });

        txtreponse.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtreponse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtreponseActionPerformed(evt);
            }
        });
        txtreponse.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtreponseKeyReleased(evt);
            }
        });

        Update.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Update.setText("Confirmer");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        txtnew.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtnew.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnewKeyReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Confirmer le mot de passe");

        txtconfirm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtconfirm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtconfirmKeyReleased(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 102, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(240, 240, 240));
        jButton1.setText("Se connecter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        search.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        search.setForeground(new java.awt.Color(240, 240, 240));
        search.setText("Rechercher");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Annuler");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 0, 0));
        jLabel22.setText("Veuillez saisir un mot de passe en alphanumérique");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(81, 81, 81))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(txtemail)
                                    .addComponent(jLabel3)
                                    .addComponent(txtquestion)
                                    .addComponent(txtreponse)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addGap(119, 119, 119)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Update))
                                    .addComponent(txtnew, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
                                    .addComponent(txtconfirm))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                                .addComponent(search)
                                .addGap(24, 24, 24))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel2)
                .addGap(92, 92, 92)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtquestion, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtreponse, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtnew, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addGap(50, 50, 50)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtconfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Update, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1572, 1007));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtreponseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtreponseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtreponseActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
   String email_user;
        email_user = txtemail.getText();
    String Q = txtquestion.getText();
    
    String Reponse = txtreponse.getText();
    String pass = txtnew.getText();
    String Confirm = txtconfirm.getText();
    
    
    String sql = "Select Reponse from client where Question_securite like '"+Q+"' ";
    
    String R = null;
    int i = 0;
    if(Confirm.equals(pass)){
        
        try {
            
            prepared = conx.prepareStatement(sql);
            resultat = prepared.executeQuery();
            
            while(resultat.next()){
                
                R = resultat.getString("Reponse");
                
                if(Reponse.equals(R)){
                    
                    Modifier(pass, email_user);
                    
                    
                   
                }
                    
                    else {
                        
            JOptionPane.showMessageDialog(null, "Reponse fausse, Reessayer", "Message", JOptionPane.ERROR_MESSAGE);

                    }
                }
                
               
            }

         catch (SQLException ex) {
            Logger.getLogger(Forgot_pass.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    else {
        
        JOptionPane.showMessageDialog(null, "Confirmation incorrecte, Reessayer", "Message", JOptionPane.ERROR_MESSAGE);

    }
    
    

         // String sql = "Select profession from client where Email like '"+email+"'";

      
//
//else {
//    
//              JOptionPane.showMessageDialog(null, "Compte introuvable, Reessayer", "Message", JOptionPane.ERROR_MESSAGE);
//
//}
//// TODO add your handling code here:
//        } catch (SQLException ex) {
//           // Logger.getLogger(Forgot_pass.class.getName()).log(Level.SEVERE, null, ex);
//           ex.printStackTrace();
//        }


    }//GEN-LAST:event_UpdateActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed

// Rechercher

String email_user;

email_user = txtemail.getText();

 String sql = "Select Question_securite from client Where EMAIL like '"+email_user+"' ";  

   try {
            prepared = conx.prepareStatement(sql);
            resultat = prepared.executeQuery();
           
           String Q = null;
           int i = 0;
            while(resultat.next()){
                
              Q = resultat.getString("Question_securite");
              
              i = 1;}
            
          if(i == 1){
              
                      txtquestion.setEnabled(true);
                       txtquestion.setText(Q);
 
          }
          else {
              
                            JOptionPane.showMessageDialog(null, "Compte introuvable, Reessayer", "Message", JOptionPane.ERROR_MESSAGE);

          }
          
         

          
        } catch (SQLException ex) {
            Logger.getLogger(Forgot_pass.class.getName()).log(Level.SEVERE, null, ex);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
clear();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtquestionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtquestionKeyReleased
              validateFields();
       
// TODO add your handling code here:
    }//GEN-LAST:event_txtquestionKeyReleased

    private void txtreponseKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtreponseKeyReleased
        
        validateFields();
// TODO add your handling code here:
    }//GEN-LAST:event_txtreponseKeyReleased

    private void txtnewKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnewKeyReleased
        
validateFields();
// TODO add your handling code here:
    }//GEN-LAST:event_txtnewKeyReleased

    private void txtconfirmKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtconfirmKeyReleased
       
validateFields();        
// TODO add your handling code here:
    }//GEN-LAST:event_txtconfirmKeyReleased

    private void txtemailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtemailKeyReleased
validateEmail(); 
validateFields();// TODO add your handling code here:
    }//GEN-LAST:event_txtemailKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Login Connexion = new Login();
        this.hide();
Connexion.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Forgot_pass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Forgot_pass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Forgot_pass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Forgot_pass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Forgot_pass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Update;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private java.awt.Panel panel1;
    private javax.swing.JButton search;
    private javax.swing.JPasswordField txtconfirm;
    private javax.swing.JTextField txtemail;
    private javax.swing.JPasswordField txtnew;
    private javax.swing.JTextField txtquestion;
    private javax.swing.JTextField txtreponse;
    // End of variables declaration//GEN-END:variables

  
}
