/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import java.awt.*;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;


/**
 *
 * @author hp
 */
public class Sign_up extends javax.swing.JFrame {

    /**
     * Creates new form Sign_up
     */
       Connection conx = null;
        ResultSet resultat = null;
        PreparedStatement prepared = null;
        String emailPattern = "^[a-zA-Z-0-9]+[@]+[a-zA-Z]+[.]+[a-zA-Z]+$";
        String passwordPattern = "^[a-zA-Z]+[0-9]+$";
        String Number_Pattern = "^[0-9]+$";
    public Sign_up() {
        initComponents();
        
         Inscrire.setEnabled(false);
         Inscrire.setBackground(new Color(240, 240, 240));
         Inscrire.setForeground(new Color(0, 0, 0));
        
//this.setExtentedStates(JFrame.MAXIMIZED_BOTH);
this.setExtendedState(JFrame.MAXIMIZED_BOTH);
conx = ConnexionMySQL.ConnectDb();
    }
    
    public void clear(){
        
         txtcni.setText("");
 txtpermis.setText("");
 txtnom.setText("");
 txtprofession.setText("");
 txtage.setText("");
 txtadr.setText("");
 txtmail.setText("");
 txttel.setText("");
 txtmot.setText("");
 txtconfirm.setText("");
 txtquestion.setText("");
txtreponse.setText("");

validateFields();
    }
    
    /*
    public String Encrypt(String T){
        
       
String A = "";        
       
        char[] chars = T.toCharArray();
        
        for(char c : chars){
            
            c += 5;
           
           // System.out.print(c);
            A = A + c;
        }

            return A;
        
        
    
    }*/
    
        public void validateFields(){

String CNI = txtcni.getText();
String permis = txtpermis.getText();
String Nom = txtnom.getText();
String Profession = txtprofession.getText();
String Age = txtage.getText();
String Adresse = txtadr.getText();
String Mail = txtmail.getText();
String Telephone = txttel.getText();
String Mot_passe = txtmot.getText();
String Confirm = txtconfirm.getText();
String Question = txtquestion.getText();
String Reponse = txtreponse.getText();


if((!CNI.equals("")) && (!permis.equals("")) && (!Nom.equals("")) && (!Profession.equals("")) && (!Age.equals("")) && (!Adresse.equals("")) && (!Mail.equals("")) && (!Telephone.equals("")) && (!Mot_passe.equals("")) && (!Confirm.equals("")) && (!Question.equals("")) && (!Reponse.equals(""))){

 Inscrire.setEnabled(true);
 Inscrire.setBackground(new Color(204, 102, 0));
 Inscrire.setForeground(new Color(240, 240, 240));
   
    
}

else {
    
     Inscrire.setEnabled(false);
 Inscrire.setBackground(new Color(240, 240, 240));
 Inscrire.setForeground(new Color(0, 0, 0));
}

        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        panel1 = new java.awt.Panel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtcni = new javax.swing.JTextField();
        txtpermis = new javax.swing.JTextField();
        txtnom = new javax.swing.JTextField();
        txtage = new javax.swing.JTextField();
        txtadr = new javax.swing.JTextField();
        txtmail = new javax.swing.JTextField();
        txtquestion = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Inscrire = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtprofession = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txttel = new javax.swing.JTextField();
        txtreponse = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtmot = new javax.swing.JPasswordField();
        txtconfirm = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registration");

        panel1.setBackground(new java.awt.Color(204, 102, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1700918001206.jpg"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Vivaldi", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Louez vite, partez plus loin");

        jLabel17.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(240, 240, 240));
        jLabel17.setText("Facebook :https://facebook/RenForYou.com");

        jLabel18.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(240, 240, 240));
        jLabel18.setText("Téléphone : +25377585576");

        jLabel19.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(240, 240, 240));
        jLabel19.setText("E-mail : rentfortou@gmail.com");

        jLabel20.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(240, 240, 240));
        jLabel20.setText("Adresse : Quartier 5 Boulevard De Gaulle Rue Farahad");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel6)))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel20)
                .addGap(38, 38, 38))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 102, 0));
        jLabel2.setText("Inscription");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("CNI");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Numéro du permis");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Nom et prénom");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Age");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("E-mail");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Adresse");

        txtcni.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtcni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcniKeyReleased(evt);
            }
        });

        txtpermis.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtpermis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpermisActionPerformed(evt);
            }
        });
        txtpermis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpermisKeyReleased(evt);
            }
        });

        txtnom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtnom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomActionPerformed(evt);
            }
        });
        txtnom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnomKeyReleased(evt);
            }
        });

        txtage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtageKeyReleased(evt);
            }
        });

        txtadr.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtadr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtadrActionPerformed(evt);
            }
        });
        txtadr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtadrKeyReleased(evt);
            }
        });

        txtmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtmailKeyReleased(evt);
            }
        });

        txtquestion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtquestion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtquestionKeyReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Numéro du téléphone");

        Inscrire.setBackground(new java.awt.Color(204, 102, 0));
        Inscrire.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Inscrire.setForeground(new java.awt.Color(240, 240, 240));
        Inscrire.setText("S'inscrire");
        Inscrire.setPreferredSize(new java.awt.Dimension(73, 27));
        Inscrire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InscrireActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Profession");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Mot de passe");

        txtprofession.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtprofession.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtprofessionKeyReleased(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("J'ai déjà un compte");

        jButton2.setBackground(new java.awt.Color(204, 102, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(240, 240, 240));
        jButton2.setText("Se connecter");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Question de securité");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Réponse");

        txttel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txttel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txttelKeyReleased(evt);
            }
        });

        txtreponse.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtreponse.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtreponseKeyReleased(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Confirmer le mot de passe");

        txtmot.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtmot.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtmotKeyReleased(evt);
            }
        });

        txtconfirm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtconfirm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtconfirmKeyReleased(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Annuler");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 0, 0));
        jLabel21.setText("Veuillez saisir un mot de passe en alphanumérique");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(txtpermis, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(txtage, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11)
                                .addComponent(txtprofession, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(txttel, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(42, 42, 42)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(txtcni, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtquestion, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(txtadr, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtmail, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addComponent(txtreponse, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtmot, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel15)
                            .addComponent(jLabel12)
                            .addComponent(jLabel16)
                            .addComponent(txtconfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(395, 395, 395))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(Inscrire, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(52, 52, 52))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel2)
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcni, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtadr, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpermis, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmail, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtquestion, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtage, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtreponse, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtprofession, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmot, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtconfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Inscrire, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );
    }// </editor-fold>                        

    private void txtnomActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void txtpermisActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void txtadrActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void InscrireActionPerformed(java.awt.event.ActionEvent evt) {                                         
String CNI = txtcni.getText();
String permis = txtpermis.getText();
String Nom = txtnom.getText();
String Profession = txtprofession.getText();
String Age = txtage.getText();
String Adresse = txtadr.getText();
String Mail = txtmail.getText();
String Telephone = txttel.getText();
String Mot_passe = txtmot.getText();
String Confirm = txtconfirm.getText();
String Question = txtquestion.getText();
String Reponse = txtreponse.getText();
String sql = "";
int i = 0;

sql = "select CNI from client_supprimes";

           try {
               prepared = conx.prepareStatement(sql);
               resultat = prepared.executeQuery();
               while(resultat.next()){
                   
                   if(CNI.equals(resultat.getString("CNI"))){
                       
                       i = 1;
                   }
                   
                  
               }
           } catch (SQLException ex) {
               Logger.getLogger(Sign_up.class.getName()).log(Level.SEVERE, null, ex);
           }
           
           if(i == 0){
               
                if(permis.matches(Number_Pattern)){
        
         if(CNI.matches(Number_Pattern)){
        
             
    if(Age.matches(Number_Pattern)){
        
          if(Telephone.matches(Number_Pattern)){
            
             if(Mail.matches(emailPattern)){
        
          if(Mot_passe.matches(passwordPattern)){
        
               if(Mot_passe.equals(Confirm)){
             
               Mot_passe = Encryption.Crypt(Mot_passe, "Key");  // mot de passe crypté

             
               sql = "Insert into client(CNI, n°permis, nom_prenom, profession, age, adresse, Telephone , Email, Question_securite, Reponse, Mot_de_passe)" + "values ('"+CNI+"', '"+permis+"', '"+Nom+"', '"+Profession+"', '"+Age+"', '"+Adresse+"', '"+Telephone+"', '"+Mail+"','"+Question+"', '"+Reponse+"', '"+Mot_passe+"')";
 
  
         
             
               try {
               
               prepared = conx.prepareStatement(sql);
               prepared.executeUpdate(sql);

              
                   
 JOptionPane.showMessageDialog(this, "Compte inscrit");

               Login Connexion = new Login();
               this.hide();
               Connexion.setVisible(true); 
                                 // Informations sur l'expéditeur
                   String senderEmail = "rentforyou599@gmail.com"; // Remplacez par votre adresse e-mail
                   String password = "fdhw tyjz xehl aabx"; // Remplacez par votre mot de passe MAHPAPA77186866
                   String recipientEmail = Mail; // Adresse e-mail du destinataire

                   // Configuration des propriétés
                   Properties props = new Properties();
                   props.put("mail.smtp.auth", "true");
                   props.put("mail.smtp.starttls.enable", "true");
                   props.put("mail.smtp.host", "smtp.gmail.com"); // Serveur SMTP pour Gmail
                   props.put("mail.smtp.port", "587"); // Port SMTP pour Gmail

                   // Création d'une session
                   Session session = Session.getInstance(props,
                           new javax.mail.Authenticator() {
                               @Override
                               protected PasswordAuthentication getPasswordAuthentication() {
                                   return new PasswordAuthentication(senderEmail, password);
                               }
                           });

                   try {
                       // Création de l'objet Message
                       Message message = new MimeMessage(session);
                       message.setFrom(new InternetAddress(senderEmail));
                       message.setRecipients(Message.RecipientType.TO, InternetAddress.parse(recipientEmail));
                       message.setSubject("Agence RentForYou");
                       message.setText("Cher(e) "+Nom+",\n" +
                               "\n" +
                               "Bienvenue chez RentForYou ! Merci pour votre inscription.\n" +
                               "\n" +
                               "Chez RentForYou, nous vous offrons une expérience de location de voiture exceptionnelle et personnalisée. Explorez notre gamme de véhicules, profitez de nos offres spéciales et partez plus loin, plus vite.\n" +
                               "\n" +
                               "Besoin d'aide ou de conseils ? Notre équipe est là pour vous accompagner.\n" +
                               "\n" +
                               "Au plaisir de vous voir sur la route,\n" +
                               "\n" +
                               "L'équipe RentForYou");

                       // Envoi de l'e-mail
                       Transport.send(message);
                               System.out.println("L'e-mail a été envoyé avec succès.");

                   } catch (MessagingException e) {
                       System.out.println("Une erreur s'est produite lors de l'envoi de l'e-mail : " + e.getMessage());
                   }
              
            // TODO add your handling code here:
               } catch (SQLException e) {
               System.out.println(e);
               }
               
               
              


               }
    
               else {
        
              JOptionPane.showMessageDialog(null, "Confirmation du mot de passe est incorrect", "Erreur", JOptionPane.ERROR_MESSAGE);

               }
  
        
           }
    
           else {  //Verification du format email
        
              JOptionPane.showMessageDialog(null, "Format du mot de passe est incorrect", "Erreur", JOptionPane.ERROR_MESSAGE);

           }
      }
      else {
              JOptionPane.showMessageDialog(null, "Format de l'e-mail est incorrect", "Erreur", JOptionPane.ERROR_MESSAGE);

          
      }
        }
        
        else {
            
              JOptionPane.showMessageDialog(null, "Format du téléphone est incorrect", "Erreur", JOptionPane.ERROR_MESSAGE);

        }
          
        
        
    }
    
    else {
        
                      JOptionPane.showMessageDialog(null, "Format de l'age est incorrect", "Erreur", JOptionPane.ERROR_MESSAGE);

    }
    }
    
    else {
        
                              JOptionPane.showMessageDialog(null, "Format du CNI est incorrect", "Erreur", JOptionPane.ERROR_MESSAGE);

    }
    }
    
    else{
        
       JOptionPane.showMessageDialog(null, "Format du permis est incorrect", "Erreur", JOptionPane.ERROR_MESSAGE);

    }
        
   
   
      
     
           }
           
           else {
               
       JOptionPane.showMessageDialog(null, "Votre compte a été supprimé", "Erreur", JOptionPane.ERROR_MESSAGE);
           }

   
  //Fermeture de la condition qui verifie si tous les champs sont remplies

    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
Login Connexion = new Login();
this.hide();
Connexion.setVisible(true); 

// TODO add your handling code here:
    }                                        

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         


clear();// TODO add your handling code here:
    }                                        

    private void txtcniKeyReleased(java.awt.event.KeyEvent evt) {                                   
validateFields();        // TODO add your handling code here:
    }                                  

    private void txtpermisKeyReleased(java.awt.event.KeyEvent evt) {                                      
validateFields();        // TODO add your handling code here:
    }                                     

    private void txtnomKeyReleased(java.awt.event.KeyEvent evt) {                                   
validateFields();        // TODO add your handling code here:
    }                                  

    private void txtageKeyReleased(java.awt.event.KeyEvent evt) {                                   
validateFields();        // TODO add your handling code here:
    }                                  

    private void txtprofessionKeyReleased(java.awt.event.KeyEvent evt) {                                          
validateFields();        // TODO add your handling code here:
    }                                         

    private void txttelKeyReleased(java.awt.event.KeyEvent evt) {                                   
validateFields();        // TODO add your handling code here:
    }                                  

    private void txtadrKeyReleased(java.awt.event.KeyEvent evt) {                                   
validateFields();        // TODO add your handling code here:
    }                                  

    private void txtmailKeyReleased(java.awt.event.KeyEvent evt) {                                    
validateFields();        // TODO add your handling code here:
    }                                   

    private void txtquestionKeyReleased(java.awt.event.KeyEvent evt) {                                        
validateFields();        // TODO add your handling code here:
    }                                       

    private void txtreponseKeyReleased(java.awt.event.KeyEvent evt) {                                       
validateFields();        // TODO add your handling code here:
    }                                      

    private void txtmotKeyReleased(java.awt.event.KeyEvent evt) {                                   
validateFields();        // TODO add your handling code here:
    }                                  

    private void txtconfirmKeyReleased(java.awt.event.KeyEvent evt) {                                       
validateFields();        // TODO add your handling code here:
    }                                      

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sign_up().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton Inscrire;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private java.awt.Panel panel1;
    private javax.swing.JTextField txtadr;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtcni;
    private javax.swing.JPasswordField txtconfirm;
    private javax.swing.JTextField txtmail;
    private javax.swing.JPasswordField txtmot;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txtpermis;
    private javax.swing.JTextField txtprofession;
    private javax.swing.JTextField txtquestion;
    private javax.swing.JTextField txtreponse;
    private javax.swing.JTextField txttel;
    // End of variables declaration                   
}
