/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import java.awt.*;
import java.sql.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class Gestion_client extends javax.swing.JFrame {

    Connection conx = null;
    PreparedStatement prepared = null;
    ResultSet resultat = null;
  
    
    /**
     * Creates new form Gestion_client
     */
    public Gestion_client() {
        
        conx = ConnexionMySQL.ConnectDb();
        
        
      this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        setTitle("Gestion des clients");
        
        initComponents();
        Search.setEnabled(false);
        Drop.setEnabled(false);
        
       Search.setForeground(new Color(0, 0, 0));
       Drop.setForeground(new Color(0, 0, 0));

        cni.setEditable(false);
        permis.setEditable(false);
        nom.setEditable(false);
        age.setEditable(false);
        profession.setEditable(false);
        tel.setEditable(false);
        adr.setEditable(false);
        mail.setEditable(false);
        question.setEditable(false);
        reponse.setEditable(false);
        mot.setEditable(false);
        
        table();
        
    }
    
    public void clear(){
        
        num_cli.setText("");
        cni.setText("");
        permis.setText("");
        nom.setText("");
        age.setText("");
        profession.setText("");
        tel.setText("");
        adr.setText("");
        mail.setText("");
        question.setText("");
        reponse.setText("");
        mot.setText("");
        
            Search.setEnabled(false);
            Search.setBackground(new Color(240, 240, 240));
            Search.setForeground(new Color(0, 0, 0));
            
            Drop.setEnabled(false);
            Drop.setBackground(new Color(240, 240, 240));
            Drop.setForeground(new Color(0, 0, 0));
            
            
        
     
     
        Table.clearSelection();
        
    }
    
    public void validate_Search_Drop(){
        String cli = num_cli.getText();
   
        if(!cli.equals("")){
            
            Search.setEnabled(true);
            Search.setBackground(new Color(204, 102, 0));
            Search.setForeground(new Color(240, 240, 240));
            
            Drop.setEnabled(true);
            Drop.setBackground(new Color(204, 102, 0));
            Drop.setForeground(new Color(240, 240, 240));
        }
        
        else {
            
            Search.setEnabled(false);
            Search.setBackground(new Color(240, 240, 240));
            Search.setForeground(new Color(0, 0, 0));
            
            Drop.setEnabled(false);
            Drop.setBackground(new Color(240, 240, 240));
            Drop.setForeground(new Color(0, 0, 0));
            
            clear();
        }
         
    }
    
      public void table(){
    
    String sql = "Select * from client";
    int c;
   
    try {
        prepared = conx.prepareStatement(sql);
         resultat = prepared.executeQuery();
            
            ResultSetMetaData rd = resultat.getMetaData();
            c = rd.getColumnCount();
            DefaultTableModel df = (DefaultTableModel)Table.getModel();
            df.setRowCount(0);
            
            
            while(resultat.next()){
                
                Vector v2 = new Vector();
               
                for(int i = 0; i < c; i++){
                    
                    v2.add(resultat.getInt("n°client"));
                    v2.add(resultat.getInt("CNI"));
                    v2.add(resultat.getInt("n°permis"));
                    v2.add(resultat.getString("nom_prenom"));
                    v2.add(resultat.getInt("age"));
                    v2.add(resultat.getString("profession"));
                    v2.add(resultat.getString("adresse"));
                    v2.add(resultat.getInt("Telephone"));
                    v2.add(resultat.getString("Email"));
                    v2.add(resultat.getString("Question_securite"));
                    v2.add(resultat.getString("Reponse"));
                    v2.add(resultat.getString("Mot_de_passe"));

                
                
                }
                
                df.addRow(v2);
                
            }
            
 
    } catch (SQLException ex) {
        Logger.getLogger(Gestion_client.class.getName()).log(Level.SEVERE, null, ex);
    }
           
}
    
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cni = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        permis = new javax.swing.JTextField();
        num_cli = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        profession = new javax.swing.JTextField();
        nom = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        tel = new javax.swing.JTextField();
        adr = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        mail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        question = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        reponse = new javax.swing.JTextField();
        Drop = new javax.swing.JButton();
        Search = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        mot = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(2500, 1701));

        cni.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cniKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("N°permis");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("N°client");

        permis.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        permis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                permisKeyReleased(evt);
            }
        });

        num_cli.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        num_cli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                num_cliKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Nom et prénom");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("CNI");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Adresse");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Numéro de téléphone");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Age");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Profession");

        profession.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        profession.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                professionKeyReleased(evt);
            }
        });

        nom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nomKeyReleased(evt);
            }
        });

        age.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        age.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ageKeyReleased(evt);
            }
        });

        tel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telActionPerformed(evt);
            }
        });

        adr.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        adr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adrActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("E-mail");

        mail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Question de sécurité");

        question.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Réponse");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Mot de passe");

        reponse.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        Drop.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Drop.setText("Supprimer");
        Drop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DropActionPerformed(evt);
            }
        });

        Search.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Search.setText("Rechercher");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });

        Cancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Cancel.setText("Annuler");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        Back.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Back.setText("Retour");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        Table.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N°client", "CNI", "N°permis", "Nom et prénom", "Age", "Profession", "Adresse", "Numéro du téléphone", "E-mail", "Question de sécurité", "Réponse", "Mot de passe"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table);
        if (Table.getColumnModel().getColumnCount() > 0) {
            Table.getColumnModel().getColumn(0).setResizable(false);
            Table.getColumnModel().getColumn(0).setPreferredWidth(100);
            Table.getColumnModel().getColumn(1).setResizable(false);
            Table.getColumnModel().getColumn(1).setPreferredWidth(50);
            Table.getColumnModel().getColumn(2).setResizable(false);
            Table.getColumnModel().getColumn(2).setPreferredWidth(50);
            Table.getColumnModel().getColumn(3).setResizable(false);
            Table.getColumnModel().getColumn(3).setPreferredWidth(90);
            Table.getColumnModel().getColumn(4).setResizable(false);
            Table.getColumnModel().getColumn(4).setPreferredWidth(50);
            Table.getColumnModel().getColumn(5).setResizable(false);
            Table.getColumnModel().getColumn(5).setPreferredWidth(50);
            Table.getColumnModel().getColumn(6).setResizable(false);
            Table.getColumnModel().getColumn(6).setPreferredWidth(50);
            Table.getColumnModel().getColumn(7).setResizable(false);
            Table.getColumnModel().getColumn(7).setPreferredWidth(75);
            Table.getColumnModel().getColumn(8).setResizable(false);
            Table.getColumnModel().getColumn(8).setPreferredWidth(120);
            Table.getColumnModel().getColumn(9).setResizable(false);
            Table.getColumnModel().getColumn(9).setPreferredWidth(50);
            Table.getColumnModel().getColumn(10).setResizable(false);
            Table.getColumnModel().getColumn(10).setPreferredWidth(50);
            Table.getColumnModel().getColumn(11).setResizable(false);
            Table.getColumnModel().getColumn(11).setPreferredWidth(50);
        }

        jButton5.setBackground(new java.awt.Color(204, 102, 0));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(240, 240, 240));
        jButton5.setText("Déconnexion");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setText("Actualiser");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        mot.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(cni, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                            .addComponent(permis)
                            .addComponent(nom)
                            .addComponent(num_cli))
                        .addGap(44, 44, 44)
                        .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel10)
                                .addComponent(jLabel9)
                                .addComponent(jLabel7)
                                .addComponent(profession, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                                .addComponent(adr)
                                .addComponent(age))
                            .addComponent(jLabel8)
                            .addComponent(tel, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(200, 200, 200)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(question, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reponse, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mot, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                            .addComponent(mail, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1525, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Drop, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73)
                                .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(175, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(167, 167, 167))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num_cli, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mail, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cni, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(profession, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(question, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(permis, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adr, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reponse, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(tel, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE))
                            .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mot, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Drop, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(68, 68, 68)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(255, 255, 255))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 2036, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, 1212, 1212, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setBounds(0, 0, 2054, 1259);
    }// </editor-fold>//GEN-END:initComponents

    private void cniKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cniKeyReleased
              // TODO add your handling code here:
    }//GEN-LAST:event_cniKeyReleased

    private void permisKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_permisKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_permisKeyReleased

    private void num_cliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_num_cliKeyReleased
validate_Search_Drop();        // TODO add your handling code here:
    }//GEN-LAST:event_num_cliKeyReleased

    private void professionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_professionKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_professionKeyReleased

    private void nomKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_nomKeyReleased

    private void ageKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ageKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_ageKeyReleased

    private void adrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adrActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
String cli = num_cli.getText();

String sql = "Select * from client where n°client like '"+cli+"' ";

        try {
            prepared = conx.prepareStatement(sql);
            resultat = prepared.executeQuery();
            
            int i = 0;
            
            while(resultat.next()){
                
            cni.setText(resultat.getString("CNI"));
            permis.setText(resultat.getString("n°permis"));
            nom.setText(resultat.getString("nom_prenom"));
            age.setText(resultat.getString("age"));
            profession.setText(resultat.getString("profession"));
            adr.setText(resultat.getString("adresse"));
            mail.setText(resultat.getString("Email"));
            tel.setText(resultat.getString("Telephone"));
            question.setText(resultat.getString("Question_securite"));
            reponse.setText(resultat.getString("Reponse"));      
            mot.setText(resultat.getString("Mot_de_passe"));
       
            i = 1;
            
            }
            
            if(i == 0){
               JOptionPane.showMessageDialog(null, "Client introuvable");
            }
            
       
        } 
            
         catch (SQLException ex) {
            Logger.getLogger(Gestion_client.class.getName()).log(Level.SEVERE, null, ex);
        }

   


// TODO add your handling code here:
    }//GEN-LAST:event_SearchActionPerformed

    private void DropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DropActionPerformed
         //  String CNI = cni.getText();
          String cli = num_cli.getText();
            int i = 0;
             
            String sql = "Select * From client where n°client like '"+cli+"' ";

     try {
        prepared = conx.prepareStatement(sql);
        resultat = prepared.executeQuery();
        
       
        while(resultat.next()){
            
            i = 1;
        }
     }
     
     catch (SQLException ex) {
System.out.println(ex); 
    
    }
     
     if(i == 1){
         
             int a = JOptionPane.showConfirmDialog(null, "Voulez-vous vraiment supprimer ce client ?", "Suppression", JOptionPane.YES_NO_OPTION);

if(a == 0){
    
    sql = "insert into client_supprimes select * from client where n°client like '"+cli+"' ";



    try {
        prepared = conx.prepareStatement(sql);
        prepared.executeUpdate();
        sql = "Delete from client where  n°client like '"+cli+"' ";
        prepared = conx.prepareStatement(sql);
        prepared.executeUpdate();
        
        
        JOptionPane.showMessageDialog(null, "Client supprimé avec succès");
        
       
clear();
table();
        
    } catch (SQLException ex) {
System.out.println(ex); 
    
    }


}
     
     }
     
     else {
         
         JOptionPane.showMessageDialog(null, "Client inexistant");
     }


// TODO add your handling code here:
    }//GEN-LAST:event_DropActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
clear();


// TODO add your handling code here:
    }//GEN-LAST:event_CancelActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
Login Connexion = new Login();
this.hide();
Connexion.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
clear();
table();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
Acceuil a = new Acceuil();
this.hide();
a.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_BackActionPerformed

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked

DefaultTableModel d1 = (DefaultTableModel)Table.getModel();

int selectIndex = Table.getSelectedRow();

num_cli.setText(d1.getValueAt(selectIndex, 0).toString());
cni.setText(d1.getValueAt(selectIndex, 1).toString());
permis.setText(d1.getValueAt(selectIndex, 2).toString());
nom.setText(d1.getValueAt(selectIndex, 3).toString());
age.setText(d1.getValueAt(selectIndex, 4).toString());
profession.setText(d1.getValueAt(selectIndex, 5).toString());
adr.setText(d1.getValueAt(selectIndex, 6).toString());
tel.setText(d1.getValueAt(selectIndex, 7).toString());
mail.setText(d1.getValueAt(selectIndex, 8).toString());
question.setText(d1.getValueAt(selectIndex, 9).toString());
reponse.setText(d1.getValueAt(selectIndex, 10).toString());
mot.setText(d1.getValueAt(selectIndex, 11).toString());



   validate_Search_Drop();

        // TODO add your handling code here:
    }//GEN-LAST:event_TableMouseClicked

    private void telActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gestion_client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gestion_client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gestion_client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gestion_client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gestion_client().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Cancel;
    private javax.swing.JButton Drop;
    private javax.swing.JButton Search;
    private javax.swing.JTable Table;
    private javax.swing.JTextField adr;
    private javax.swing.JTextField age;
    private javax.swing.JTextField cni;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mail;
    private javax.swing.JTextField mot;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField num_cli;
    private javax.swing.JTextField permis;
    private javax.swing.JTextField profession;
    private javax.swing.JTextField question;
    private javax.swing.JTextField reponse;
    private javax.swing.JTextField tel;
    // End of variables declaration//GEN-END:variables
}
